version: '2'

services:
  redis:
    image: redis:alpine

  web:
    build:
      context: .
    restart: always
    volumes:
      - $PWD:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: python run.py

  worker:
    build:
      context: .
    volumes:
      - $PWD:/app
      - $PWD/validator/tests/data:/app/data
    depends_on:
      - redis
      - spark
    command: celery worker -A service.celery --loglevel=info

  spark:
    build:
      context: ./validator
    command: bin/bootstrap.sh
    hostname: master
    environment:
      MASTER: spark://master:7077
    expose:
      - 6066
      - 7077
    ports:
      - "8080:8080"
    volumes:
      - $PWD/validator/tests/data:/app/data