version: '2'

services:
  redis:
    image: redis:alpine

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - $PWD:/app
      - $PWD/validator/tests/data:/mnt/data
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - spark
    command: python run.py

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - $PWD:/app
    depends_on:
      - redis
    command: celery worker -A service.celery --loglevel=info

  spark:
    build:
      context: ./validator
    command: bin/bootstrap.sh
    hostname: master
    environment:
      MASTER: spark://master:7077
      #SPARK_CONF_DIR: /conf
      #SPARK_PUBLIC_DNS: localhost
    expose:
      - 6066
      - 7077
    ports:
      - "8080:8080"
    volumes:
      # - $PWD/conf/master:/conf
      - $PWD/validator/tests/data:/mnt/data